---
title: "Univariate Assignment"
author: "Nick Weber"
date: "1/24/2018"
output: html_document
---

```{r}
#1. Explanatory analysis for Acer rubrum and Abies fraseri...

library(car)
trees <- read.csv("treedata_subset.csv", header=TRUE)

#ACER RUBRUM

a <- trees$elev[trees$species=="Acer rubrum"]
b <- trees$tci[trees$species=="Acer rubrum"]
c <- trees$streamdist[trees$species=="Acer rubrum"]
d <- trees$disturb[trees$species=="Acer rubrum"]
e <- trees$beers[trees$species=="Acer rubrum"]

acer_mod1 <- lm(cover[species=="Acer rubrum"] ~ a + b + c + as.factor(d) + e, data=trees)
summary(acer_mod1) #Adj.R2=0.036
Anova(acer_mod1, type=3)

#The p-values generated by Anova() are the same as those generated by summary(). However, summary() generates p-values for all of the categories in "disturb", while Anova() groups those categories into one p-value. 

pairs(cover[species=="Acer rubrum"] ~ a + b + c + as.factor(d) + e, data=trees, panel=panel.smooth)

#Removing least sig term first (d <- disturb)...

acer_mod2 <- lm(cover[species=="Acer rubrum"] ~ a + b + c + e, data=trees)
summary(acer_mod2) #Adj.R2=0.036
Anova(acer_mod2, type=3)

#Again removing least sig term (b <- tci)...

acer_mod3 <- lm(cover[species=="Acer rubrum"] ~ a + c + e, data=trees)
summary(acer_mod3) #All terms (a, c, e) are significant, but Adj.R2=0.033
Anova(acer_mod3, type=3)

#Let's look at that same model, but accounting for potential interactions...

acer_modinteract <- lm(cover[species=="Acer rubrum"] ~ a + c + e + a*e, data=trees)
summary(acer_modinteract) #All terms (a, c, e, a*e) are significant, and Adj.R2=0.061
Anova(acer_modinteract, type=3)

pairs(cover[species=="Acer rubrum"] ~ a + c + e + a*e, data=trees)

#Now attempting just single variable models, with the 3 variables that were significant in the multiple regression.

acer_moda <- lm(cover[species=="Acer rubrum"] ~ a, data=trees)
summary(acer_moda) #Adj.R2=0.01

acer_modc <- lm(cover[species=="Acer rubrum"] ~ c, data=trees)
summary(acer_modc) #Adj.R2=0.01

acer_mode <- lm(cover[species=="Acer rubrum"] ~ e, data=trees)
summary(acer_mode) #Adj.R2=0.01

#For Acer rubrum, the best fitting model (acer_modinteract) contains the explanatory variables elev, streamdist, and beers, with an interaction between elev and beers. While these variables are the most important, the model does not do a very good job of explaining cover (Adj.R2=0.061).

#Checking to see if any assumptions are violated for Acer rubrum...
par(mfrow=c(2,2))
plot(acer_modinteract)

#It appears that no assumptions are violated.
```

```{r}
#ABIES FRASERI

a.fras <- trees$elev[trees$species=="Abies fraseri"]
b.fras <- trees$tci[trees$species=="Abies fraseri"]
c.fras <- trees$streamdist[trees$species=="Abies fraseri"]
d.fras <- trees$disturb[trees$species=="Abies fraseri"]
e.fras <- trees$beers[trees$species=="Abies fraseri"]

abies_mod1 <- lm(cover[species=="Abies fraseri"] ~ a.fras + b.fras + c.fras + as.factor(d.fras) + e.fras, data=trees)
summary(abies_mod1) #Adj.R2=0.50
Anova(abies_mod1, type=3)

pairs(cover[species=="Abies fraseri"] ~ a.fras + b.fras + c.fras + as.factor(d.fras) + e.fras, data=trees, panel=panel.smooth)

#Removing least sig term first (e <- beers)...

abies_mod2 <- lm(cover[species=="Abies fraseri"] ~ a.fras + b.fras + c.fras + as.factor(d.fras), data=trees)
summary(abies_mod2) #Adj.R2=0.51
Anova(abies_mod2, type=3)

#Again removing least sig term (c <- streamdist)...

abies_mod3 <- lm(cover[species=="Abies fraseri"] ~ a.fras + b.fras + as.factor(d.fras), data=trees)
summary(abies_mod3) #Adj.R2=0.52
Anova(abies_mod3, type=3)

#Again removing least sig term (d <- disturb)...

abies_mod4 <- lm(cover[species=="Abies fraseri"] ~ a.fras + b.fras, data=trees)
summary(abies_mod4) #Adj.R2=0.50
Anova(abies_mod4, type=3)

pairs(cover[species=="Abies fraseri"] ~ a.fras + b.fras, data=trees)

#Again removing least sig term (b <- tci)...

abies_mod5 <- lm(cover[species=="Abies fraseri"] ~ a.fras, data=trees)
summary(abies_mod5) #Adj.R2=0.47
Anova(abies_mod5, type=3)

#Although this final model (with only elev as an explanatory variable) has a slightly lower Adj.R2 value, it is also much less complex, and I think it could be argued that this is the best model. For Abies fraseri, the most important explnatory variable is elev. Overall, the models for the habitat specialist (Abies fraseri) do a much better job of explaining the variation in cover than the models for the habitat generalist (Acer rubrum). This is not surprising, given that the habitat specialist is a specialist for a reason, and it appears that elevation might be controlling for that. By definition, with a habitat generalist, there likely is not a single variable that can explain its distribution (or, in this case, cover).

#Checking to see if any assumptions are violated for Abies fraseri...
par(mfrow=c(2,2))
plot(abies_mod5)
```

```{r}
#2. Re-examining solutions to #1 with the perspective of a GLM...

#Best fitting model for Acer rubrum...
acer_modinteract <- lm(cover[species=="Acer rubrum"] ~ a + c + e + a*e, data=trees)
summary(acer_modinteract) #Adj.R2=0.061

acer_modinteract_glm <- glm(cover[species=="Acer rubrum"] ~ a + c + e + a*e, data=trees, family='poisson')
summary(acer_modinteract_glm)

#Best fitting model for Abies fraseri...
abies_mod5 <- lm(cover[species=="Abies fraseri"] ~ a.fras, data=trees)
summary(abies_mod5) #Adj.R2=0.47

abies_mod5_glm <- glm(cover[species=="Abies fraseri"] ~ a.fras, data=trees, family='poisson')
summary(abies_mod5_glm)

pseudo_r2 = function(glm_mod) {
     1 -  glm_mod$deviance / glm_mod$null.deviance
  }

pseudo_r2(acer_modinteract_glm) #R2=0.060
pseudo_r2(abies_mod5_glm) #R2=0.46

#Comparing the residual sums of squares between the traditional models and the GLM models...
anova(acer_modinteract, acer_modinteract_glm)
anova(abies_mod5, abies_mod5_glm)
#Chaning the error distribution did not change the results much. Both models explain approximately the same amount of variation (R2=0.033 and R2=0.032). However, moving to the poission reduced the deviance dramatially for both species...
```

```{r}
#3. Summary of results...

#For both species, I started with the most complex model (i.e. including all possible explanatory variables), and removed variables 1 by 1 (each time removing the variable with the least significance) until all variables were significant. Once I found a model with all significant variables, I began to rely more on the R2 value to find the best fitting model. In the case of Abies fraseri, the model with 2 explanatory variables (elev and tci) actually had a slightly higher AIC than the model with just 1 explanatory variable (elev). However, the difference in AIC was not much, and because a simpler model is always better, I chose the model with just 1 variable. I then plotted the final models to check for any assumption violations. Overall, it is not surprising that the variation in cover for the habitat specialist can be better explained. It is also not surprising that it could take more explanatory variables to explain the variation in cover for a habitat generalist. 
```

```{r}
#4. Stepwise regression analysis on the full model...
library(MASS)

stepAIC(acer_mod1)

#According to the stepwise AIC function, the best fitting model for Acer rubrum includes elev, tci, streamdist, and beers. This model has one more variable (tci) than my analysis above.

stepAIC(abies_mod1)

#According to the stepwise AIC function, the best fitting model for Abies fraseri includes elev and tci. This model also has one more variable (tci) than my analysis above.
```